server {
    listen 80;
    listen [::]:80;
    server_name geosurvey.eqmscl.com www.geosurvey.eqmscl.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name geosurvey.eqmscl.com www.geosurvey.eqmscl.com;

    ssl_certificate /etc/letsencrypt/live/geosurvey.eqmscl.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/geosurvey.eqmscl.com/privkey.pem;

    root /var/www/eqms-geosurvey/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 210m;
    }

    location ~* (sw\.js|registerSW\.js|manifest\.webmanifest|index\.html)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
